api-version: 1.16
name: Factions
main: ru.ostrov77.factions.Main
version: 1.0
load: POSTWORLD
author: Komiss77

depend: [Ostrov]
softdepend: [DeluxeChat]


commands:
  f:
    description: Кланы
    aliases: [factions]

